#!/usr/bin/env bash
cd
python3 -m pip install --upgrade pip
pip3 install pandas
pip3 install PySimpleGUI
pip3 install xlsxwriter
pip3 install matplotlib
pip3 install pingouin
pip3 install seaborn
pip3 install matplotlib
pip3 install scipy
pip3 install statsmodels
pip3 install pyprocessmacro
pip3 install xlrd

mkdir CORals-Analytics

cp ~/Downloads/CORals-Analytics_3.7.7/scripts/CORals-Analytics_3.7.7 ~/Desktop
cp ~/Downloads/CORals-Analytics_3.7.7/scripts/CORals-Analytics_3.7.7.py ~/CORals-Analytics
cp ~/Downloads/CORals-Analytics_3.7.7/scripts/logo.png ~/CORals-Analytics

rm ~/Downloads/CORals-Analytics_3.7.7.zip
rm -r ~/Downloads/CORals-Analytics_3.7.7

osascript -e 'tell application "Terminal" to close (every window whose name contains "CORals")' &
exit
